### PR TITLE
skip foreign key checks on migrate

### PR DESCRIPTION
**Pull request by bubenkoff**
Helps for complex structures

### CODE REVIEW

**Comment by shazow** [comment]
Isn't this specific to MySQL?

sqlalchemygrate's goal is to be agnostic of databases thanks to SQLAlchemy. :)

**Comment by bubenkoff** [comment]
i know, i agree it's kinda dirty hack

**Comment by shazow** [comment]
Good reference though, I'll leave it open in case other people look for it. :)

**Comment by bubenkoff** [comment]
but the intention is good - sqlalchemygrate could not handle relations properly when i tried to migrate the dataset, so i've ended up making this change and it worked

**Comment by bubenkoff** [comment]
i'll rewrite it to check if it's mysql

**Comment by shazow** [comment]
PostgreSQL, for example, has its own way for disabling indices/triggers which is recommended when doing huge bulk operations. I think it's something that is better left to be managed outside of sqlalchemygrate, unless we add somekind of hooks for specifying stuff like that.

To be honest, this library is not super-maintained these days. :)

**Comment by bubenkoff** [comment]
but it still works with recent alchemy!
it's really cool project, thanks a lot!

**Comment by shazow** [comment]
Glad to hear it, it's more of a testament to @zzzeek's epic backwards-compatibility. :)

**Comment by bubenkoff** [comment]
true, a bit of both :)

On 22 April 2015 at 22:57, Andrey Petrov <notifications@github.com> wrote:

> Glad to hear it, it's more of a testament to @zzzeek
> <https://github.com/zzzeek>'s epic backwards-compatibility. :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/shazow/sqlalchemygrate/pull/3#issuecomment-95333389>.
>



-- 
Anatoly Bubenkov

**Pull request closed without merging**
